name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # セットアップ
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # ビルド
      - name: ビルド
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
