name: pages
on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:

      # セットアップ
      - name: チェックアウト：src
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0
      - name: チェックアウト：dest
        uses: actions/checkout@v4
        with:
          path: dest
          ref: pages
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # ビルド
      - name: ビルド
        working-directory: src
        run: bash gradlew buildPages

      # 成果物の配置
      - name: ビルドしたものをコピー
        working-directory: dest
        run: |
          git rm -rf .
          cp -R ../src/build/pages/* .

      # リリース
      - name: リリース
        working-directory: dest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Workflow"
          git config user.email "GitHub Workflow"
          git add .
          git commit -m "From main@${{ github.sha }}" || echo "No changes to commit"
          git push origin pages --force
